---
- name: restart mosquitto
  community.docker.docker_compose_v2:
    project_src: "{{ docker_services_dir }}/{{ app_name }}"
    state: restarted
    services:
      - mosquitto

- name: restart homeassistant
  community.docker.docker_compose_v2:
    project_src: "{{ docker_services_dir }}/{{ app_name }}"
    state: restarted
    services:
      - homeassistant
