---
- name: Setup Homelab Server
  hosts: homelab
  become: true
  roles:
    - role: ubuntu-base
      tags: [base]
    - role: ubuntu-docker
      tags: [base, docker]
    - role: ubuntu-fstab
      tags: [base, fstab]
    - role: docker-homeassistant
      tags: [apps, homeassistant]
    - role: docker-dns
      tags: [apps, dns]
    - role: docker-qbittorrent
      tags: [apps, qbittorrent]
    - role: docker-jellyfin
      tags: [apps, jellyfin]
    - role: docker-stash
      tags: [apps, stash]
    - role: docker-envoy
      tags: [apps, envoy]
    - role: docker-dockhand
      tags: [apps, dockhand]
    - role: docker-scrutiny
      tags: [apps, scrutiny]
    - role: docker-immich
      tags: [apps, immich]
    - role: docker-paperless
      tags: [apps, paperless]
    - role: docker-pairdrop
      tags: [apps, pairdrop]
    - role: docker-homepage
      tags: [apps, homepage]
    - role: docker-serr
      tags: [apps, serr]
