http:
  routers:
    # Dashboard
    dashboard-web:
      service: api@internal
      rule: Host(`traefik.handystuff.net`)
      entryPoints:
        - web
      middlewares:
        - web-secure-redirect
    dashboard-web-secure:
      service: api@internal
      rule: Host(`traefik.handystuff.net`)
      entryPoints:
        - web-secure
      tls:
        certResolver: certResolver

    # Portainer
    portainer-web:
      service: portainer@docker
      rule: Host(`portainer.handystuff.net`)
      entryPoints:
        - web
      middlewares:
        - web-secure-redirect
    portainer-web-secure:
      service: portainer@docker
      rule: Host(`portainer.handystuff.net`)
      entryPoints:
        - web-secure
      tls:
        certResolver: certResolver

    # NGINX
    nginx-web:
      service: nginx@docker
      rule: Host(`vocadb-notification-reader.handystuff.net`) || Host(`niconicotagger.handystuff.net`)
      entryPoints:
        - web
      middlewares:
        - web-secure-redirect
    nginx-web-secure:
      service: nginx@docker
      rule: Host(`vocadb-notification-reader.handystuff.net`) || Host(`niconicotagger.handystuff.net`)
      entryPoints:
        - web-secure
      tls:
        certResolver: certResolver

    # VocaDB Notification Reader
    vocadb-notification-reader-web:
      service: vocadb-notification-reader@docker
      rule: Host(`api.vocadb-notification-reader.handystuff.net`)
      entryPoints:
        - web
      middlewares:
        - web-secure-redirect
    vocadb-notification-reader-web-secure:
      service: vocadb-notification-reader@docker
      rule: Host(`api.vocadb-notification-reader.handystuff.net`)
      entryPoints:
        - web-secure
      tls:
        certResolver: certResolver
      middlewares:
        - vocadb-notification-reader-cors

    # NicoNico Tagger
    niconicotagger-web:
      service: niconicotagger@docker
      rule: Host(`api.niconicotagger.handystuff.net`)
      entryPoints:
        - web
      middlewares:
        - web-secure-redirect
    niconicotagger-web-secure:
      service: niconicotagger@docker
      rule: Host(`api.niconicotagger.handystuff.net`)
      entryPoints:
        - web-secure
      tls:
        certResolver: certResolver
      middlewares:
        - niconicotagger-cors

  middlewares:
    web-secure-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    vocadb-notification-reader-cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
        accessControlAllowHeaders: [ "Accept", "Authorization", "Content-Type", "Origin" ]
        accessControlAllowOriginList:
          - https://api.vocadb-notification-reader.handystuff.net
          - https://vocadb-notification-reader.handystuff.net
        accessControlMaxAge: 600
        addVaryHeader: true
    niconicotagger-cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
        accessControlAllowHeaders: [ "Accept", "Authorization", "Content-Type", "Origin" ]
        accessControlAllowOriginList:
          - https://api.niconicotagger.handystuff.net
          - https://niconicotagger.handystuff.net
        accessControlMaxAge: 600
        addVaryHeader: true
