global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: false
  insecure: false

entryPoints:
  web:
    address: :80
  web-secure:
    address: :443

certificatesResolvers:
  certResolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: sanya.rnd@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    network: traefik
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    allowEmptyServices: false
    defaultRule: "" # https://github.com/traefik/traefik/issues/5576
  file:
    filename: /etc/traefik/routes.yml
    watch: true

accessLog:
  format: json
log:
  level: DEBUG
  format: json

metrics:
  prometheus:
    entryPoint: metrics
    addServicesLabels: true
    addEntryPointsLabels: true
