---
- name: Download 'mergerfs' installation package
  ansible.builtin.get_url:
    url: "https://github.com/trapexit/mergerfs/releases/download/{{ mounts_mergerfs_version }}/mergerfs_{{ mounts_mergerfs_version }}.{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}_amd64.deb"
    dest: "/tmp/mergerfs_{{ mounts_mergerfs_version }}.deb"
    timeout: 60
    force: false

- name: Install 'mergerfs'
  ansible.builtin.apt:
    deb: "/tmp/mergerfs_{{ mounts_mergerfs_version }}.deb"

- name: Remove .deb file
  ansible.builtin.file:
    path: "/tmp/mergerfs_{{ mounts_mergerfs_version }}.deb"
    state: absent
