---
- name: Create group for data access
  ansible.builtin.group:
    name: "{{ mounts_access_group }}"
    state: present

- name: Add users to media group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ mounts_access_group }}"
    append: yes
  loop: "{{ mounts_users }}"
