---
- name: Verify that boot drives are defined
  ansible.builtin.fail:
    msg: "You must define all the boot drives manually"
  when: mounts_boot is not defined or mounts_boot|length == 0

- name: Push out the 'fstab' file
  ansible.builtin.template:
    dest: "{{ mounts_fstab_path }}"
    src: fstab.j2
    owner: root
    group: root
    mode: "0644"

- name: Create mount points for normal drives
  ansible.builtin.file:
    path: "{{ item.mount_point }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items: "{{ mounts_normal }}"
  when: mounts_normal is defined

- name: Create mount points for drive pools
  ansible.builtin.file:
    path: "{{ item.mount_point }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items: "{{ mounts_pooled }}"
  when: mounts_pooled is defined

- name: Reload systemd to pick up changes to fstab
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Mount drives
  ansible.builtin.command: mount -a -t nofuse.mergerfs

- name: Mount pooled drives
  ansible.builtin.command: "mount --target {{ item.mount_point }}"
  with_items: "{{ mounts_pooled }}"
  when: mounts_pooled is defined
