services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - 443:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - PEERS=20
    volumes:
      - ./config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
