---
- name: Create group for docker services directory
  become: true
  ansible.builtin.group:
    name: "{{ docker_services_group }}"
    state: present

- name: Add users to docker services group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ docker_services_group }}"
    append: yes
  loop: "{{ docker_services_users }}"

- name: Create base directory for docker services
  become: true
  ansible.builtin.file:
    path: "{{ docker_services_dir }}"
    state: directory
    owner: root
    group: "{{ docker_services_group }}"
    mode: '0775'
