---
- name: install docker packages
  import_tasks: install.yml

- name: configure docker
  import_tasks: post-install.yml

- name: create directory for docker services
  import_tasks: create-docker-services-dir.yml
