---
- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_services_users }}"

- name: Enable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: yes

- name: Enable Containerd service
  become: true
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
