services:
  vocadb-notification-reader:
    image: ghcr.io/sanyarnd/vocadb-notification-reader
    container_name: vocadb-notification-reader
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.vocadb-notification-reader.service: vocadb-notification-reader
      traefik.http.services.vocadb-notification-reader.loadbalancer.server.port: 8080
    networks:
      - traefik

networks:
  traefik:
    external: true
