services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --label-enable --cleanup
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none
