services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1001:1002
    restart: unless-stopped
    group_add:
      - '44'  # getent group video | cut -d: -f3
      - '993' # getent group render | cut -d: -f3
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=Europe/Moscow
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - cache:/cache
      - config:/config
      - type: bind
        source: /mnt/media
        target: /media

volumes:
  cache:
  config:
