---
- name: install lm-sensors package
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: latest
    pkg:
      - lm-sensors

- name: detect sensors
  become: true
  ansible.builtin.command: sensors-detect --auto
