---
- name: Create temp configuration file
  ansible.builtin.copy:
    src: envoy.yaml
    dest: /tmp/envoy.yaml
    mode: '0644'

- name: Copy config to the container
  ansible.builtin.shell: docker cp /tmp/envoy.yaml envoy:/etc/envoy/custom/envoy.yaml

- name: Remove temp configuration file
  ansible.builtin.file:
    path: /tmp/envoy.yaml
    state: absent
