---
- name: Copy configuration file to app directory
  ansible.builtin.copy:
    src: envoy.yaml
    dest: "{{ docker_services_dir }}/{{ app_name }}/envoy.yaml"
    mode: '0644'
  notify: restart envoy

- name: Copy config to the container
  community.docker.docker_container_copy_into:
    container: envoy
    path: "{{ docker_services_dir }}/{{ app_name }}/envoy.yaml"
    container_path: /etc/envoy/custom/envoy.yaml
