---
- name: Copy configuration file to app directory
  ansible.builtin.copy:
    src: envoy.yaml
    dest: "{{ docker_services_dir }}/{{ app_name }}/envoy.yaml"
    mode: '0644'
  notify: restart envoy

- name: Copy config to the container
  ansible.builtin.command:
    cmd: docker cp "{{ docker_services_dir }}/{{ app_name }}/envoy.yaml" envoy:/etc/envoy/custom/envoy.yaml
