services:
  traefik:
    image: traefik:3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
    networks:
      - traefik

volumes:
  acme:

networks:
  traefik:
    external: true
