---
dialout_users: [ alex, ansible ]
docker_services_users: [ alex, ansible ]
mounts_users: [ alex, ansible ]
mounts_owner_user: ansible

# --------------------------------------
# Local Services (drives both Envoy + DNS)
# --------------------------------------
lab_domain: "home"
lab_ip: "192.168.88.88"

technitium_api_url: "http://192.168.88.88"
technitium_api_port: 5380
technitium_api_token: "{{ vault_technitium_api_token }}"

lab_services:
  - name: hass
    port: 8123
  - name: z2m
    port: 8124
  - name: jellyfin
    port: 8096
  - name: qbt
    port: 8111
  - name: stash
    port: 9999
  - name: immich
    port: 2283
  - name: paperless
    port: 8000
  - name: dockhand
    port: 3000
  - name: pairdrop
    port: 4000
  - name: scrutiny
    port: 8130
  - name: dns
    port: 5380
  - name: start
    port: 5000

# --------------------------------------
# Disks
# --------------------------------------
mounts_boot:
  - device: "/dev/disk/by-id/dm-uuid-LVM-BH8GE9gsgEvvg6oAOiwnwkpYqOv2cUdb4u7oMq6LKueF14N9cRpe0i9j81BnO2SZ"
    mount_point: "/"
    type: "ext4"
    options: defaults
    dump: 0
    pass: 1
  - device: "/dev/disk/by-uuid/975e2593-0db5-46e6-a2d1-fc2527a18a1f"
    mount_point: "/boot"
    type: "ext4"
    options: "defaults"
    dump: 0
    pass: 1
  - device: "/dev/disk/by-uuid/0874-E9F6"
    mount_point: "/boot/efi"
    type: "vfat"
    options: "defaults"
    dump: 0
    pass: 1
  - device: "/swap.img"
    mount_point: "none"
    type: "swap"
    options: "sw"
    dump: 0
    pass: 0

mounts_normal:
  - uuid: "94f3b831-0159-47d8-822e-86fd1b5f7008"
    mount_point: "/mnt/hdd1"
    type: "ext4"
    options: "defaults,nofail"
    dump: 0
    pass: 2
    comment: "8TB Seagate Enterprise 2019"

  - uuid: "68cd5296-dd92-4524-9c60-ffb43974d334"
    mount_point: "/mnt/hdd2"
    type: "ext4"
    options: "defaults,nofail"
    dump: 0
    pass: 2
    comment: "8TB Seagate Exos 2022"

  - uuid: "39414da2-9eb8-4cb7-88c0-5108355f3e48"
    mount_point: "/mnt/hdd3"
    type: "ext4"
    options: "defaults,nofail"
    dump: 0
    pass: 2
    comment: "16TB TOSHIBA MG08ACA1 2025"

  - uuid: "673cd3c3-1aa8-4e82-a13d-5da5f7c986ec"
    mount_point: "/mnt/hdd4"
    type: "ext4"
    options: "defaults,nofail"
    dump: 0
    pass: 2
    comment: "16TB TOSHIBA MG08ACA1 2025"

mounts_pooled:
  - name: "media"
    mount_point: "/mnt/media"
    dump: 0
    pass: 0
    # process-thread-count=-2: Enables a separate thread pool for processing FUSE requests.
    #   Value -2 means: number of CPU cores divided by 2 (minimum 1 thread).
    #   -1 disables separate processing threads; 0 uses core count; positive values set a fixed number.
    # read-thread-count=-2: Number of threads dedicated to reading FUSE messages from the kernel.
    #   -2 means: number of CPU cores divided by 2.
    #   Works together with process-thread-count to separate reading and processing stages.
    # lazy-umount-mountpoint=true: mergerfs will attempt to "lazy unmount" the mount point before mounting.
    #   Useful for live upgrades or avoiding mount conflicts.
    # category.create=pfrd: Policy for new file placement — selects the first branch with above-average free space.
    #   Tends to fill drives sequentially and respects branch order. Good for predictability and reducing disk spin-ups.
    # func.getattr=newest: File attributes (like mtime) are taken from the newest (most recently modified) version across branches.
    # cache.readdir=true: Enables directory entry caching, improving readdir() performance when supported.
    # cache.files=partial: Enables partial file data caching in FUSE, boosting read performance.
    #   Helps with streaming or sequential access but requires dropcacheonclose to avoid double caching.
    # dropcacheonclose=true: When a file is closed, instructs the kernel to drop its page cache.
    #   Recommended with cache.files=partial to reduce memory usage and avoid duplication.
    options: "process-thread-count=-2,read-thread-count=-2,lazy-umount-mountpoint=true,category.create=pfrd,func.getattr=newest,cache.readdir=true,cache.files=partial,dropcacheonclose=true"
    branches:
      - "/mnt/hdd1"
      - "/mnt/hdd2"
      - "/mnt/hdd3"
      - "/mnt/hdd4"


# --------------------------------------
# Vault
# --------------------------------------
vault_technitium_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37313632323633363963613837306362366265336366396130353965616337393264633530393837
          3663656163316530643266656465343234623532613433360a353066643832336465326231306337
          31373431303966656433653063613061373632303263313037633934306635383866613037643462
          6562346131306263380a653932656133666230626330633861343338326163623031326637363062
          63613437626364303233656130343830613666313136396136616530383163326634323039373139
          32393639363330656231313935343431623865396537323038663431316161346163363732343665
          65643533326165386539663035353863333931396564376137353839333364336461356537613164
          38393934393863316138
