---
- name: Copy mosquitto config to app directory
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: "{{ docker_services_dir }}/{{ app_name }}/mosquitto.conf"
    mode: '0644'
  notify: restart mosquitto

- name: Copy config to mosquitto container
  ansible.builtin.command:
    cmd: docker cp "{{ docker_services_dir }}/{{ app_name }}/mosquitto.conf" mosquitto:/mosquitto/config/mosquitto.conf
