---
- name: Install HACS
  ansible.builtin.shell: docker exec homeassistant /bin/bash -c "wget -O - https://get.hacs.xyz | bash -"
  register: hacs_result
  changed_when: "'already' not in (hacs_result.stdout + hacs_result.stderr)"
  notify: restart homeassistant
