---
- name: Start the home assistant service
  ansible.builtin.shell:
    cmd: docker compose up -d homeassistant
    chdir: "{{ docker_services_dir }}/{{ app_name }}"

- name: Install HACS
  ansible.builtin.shell: docker exec homeassistant /bin/bash -c "wget -O - https://get.hacs.xyz | bash -"

- name: Restart the home assistant
  ansible.builtin.shell:
    cmd: docker compose restart homeassistant
    chdir: "{{ docker_services_dir }}/{{ app_name }}"
