---
- name: Set compose file path for this role
  ansible.builtin.set_fact:
    compose_src_path: "{{ role_path }}/files/compose.yml"

- name: Deploy docker-compose app
  ansible.builtin.include_role:
    name: docker-common
    tasks_from: deploy.yml

- name: Configure Mosquitto
  ansible.builtin.import_tasks: configure-mosquitto.yml

- name: Install HACS
  ansible.builtin.import_tasks: configure-hacs.yml
