name: Deploy Handystuff

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/handystuff.yml
      - handystuff/**

env:
  REMOTE: handystuff.net

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: github.ref_name == 'master'
    defaults:
      run:
        working-directory: handystuff

    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          echo "${{ secrets.DEPLOY_SSH_CONFIG }}" > ~/.ssh/config
          echo "${{ secrets.DEPLOY_SSH_HOSTS }}" > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/deploy_key

      - run: ssh $REMOTE "mkdir -p ~/deploy"

      - name: Deploy Traefik
        run: |
          ssh $REMOTE "docker network create traefik || true"
          ssh $REMOTE "mkdir -p deploy/traefik"
          rsync --recursive --delete traefik/ $REMOTE:~/deploy/traefik
          ssh $REMOTE "cd ~/deploy/traefik && docker compose pull && docker compose up -d --remove-orphans"

      - name: Deploy Watchtower
        run: |
          ssh $REMOTE "mkdir -p deploy/watchtower"
          rsync --recursive --delete watchtower/ $REMOTE:~/deploy/watchtower
          ssh $REMOTE "cd ~/deploy/watchtower && docker compose pull && docker compose up -d --remove-orphans"

      - name: Deploy Portainer
        run: |
          ssh $REMOTE "mkdir -p deploy/portainer"
          rsync --recursive --delete portainer/ $REMOTE:~/deploy/portainer
          ssh $REMOTE "cd ~/deploy/portainer && docker compose pull && docker compose up -d --remove-orphans"

      - name: Deploy NGINX
        run: |
          ssh $REMOTE "mkdir -p deploy/nginx deploy/nginx/config deploy/nginx/html"
          rsync --recursive --delete nginx/config/ $REMOTE:~/deploy/nginx/config
          rsync nginx/compose.yml $REMOTE:~/deploy/nginx/compose.yml
          ssh $REMOTE "cd ~/deploy/nginx && docker compose pull && docker compose up -d --remove-orphans && docker restart nginx"

      - name: Deploy Apps
        run: |
          ssh $REMOTE "mkdir -p deploy/apps deploy/apps/config"
          rsync --recursive --delete apps/ $REMOTE:~/deploy/apps
          ssh $REMOTE "cd ~/deploy/apps && docker compose pull && docker compose up -d --remove-orphans"

#      - name: Deploy Wireguard
#        run: |
#          ssh $REMOTE "mkdir -p deploy/wireguard deploy/wireguard/config"
#          rsync wireguard/compose.yml $REMOTE:~/deploy/wireguard/compose.yml
#          ssh $REMOTE "cd ~/deploy/wireguard && docker compose pull && docker compose up -d --remove-orphans"
